# -*- coding: utf-8 -*-
"""Listed_Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VOXsT9QN_p8G3i5gXReIYbU7Jh8Zj1eL
"""

import csv
from googlesearch import search

# Define the search query and limit
query = 'site:youtube.com openinapp.co'
limit = 10000

def scrape_youtube_channels(query, limit):
    results = []

    # Perform Google search with specified query and limit
    search_results = search(query, stop = limit , pause = 2)

    # Iterate over the search results
    for result in search_results:
        # Check if the search result URL is a YouTube channel
        if 'youtube.com/channel/' in result:
            # Extract the YouTube channel URL
            channel_url = result

            # Append the YouTube channel URL to the results list
            results.append(channel_url)

    return results

# Scrape YouTube channel links from the search results
youtube_channels = scrape_youtube_channels(query, limit)

# Save the results in CSV format
with open(r'youtube_channels.csv', 'w', newline='') as csv_file:
    writer = csv.writer(csv_file)
    writer.writerow(['YouTube Channel Links'])
    writer.writerows([[channel] for channel in youtube_channels])